### ISSUE TITLE
Unexpected multivariant output on type errors

### ISSUE THREAD

**Issue by MichalMarsalek** [polygolf-lang/polygolf#248]
**Describe the bug**
There are different ways of defining a 2-variant input that should all behave the same, but they don't.

**To Reproduce**
Consider these three Polygolf programs:
1.
```
{
    $x <- 0;
    print_int $x;
/
    $x <- "x";
    print_int $x;
};
```
2.
```
{
    $x <- 0;
/
    $x <- "x";
};
print_int $x;
```

3.
```
$x <- {0 / "x"};
print_int $x;
```

These three programs are equivalent in theory.

**Expected behavior**
When compiled with `-l py -a`, we expect
```
x=0
print(x)

Type error. Operator 'print_int' type error. Expected [-oo..oo] but got [(Ascii 1..1)].
  5     $x <- "x";
  6     print_int $x;
        ^
```

**Actual behavior**
Code 1. output is the expected one.

Code 2. outputs
```
x=0
print(x)

x="x"
print(x)
```

Code 3. outputs
```
x=0
print(x)

Type error. Cannot assign (Ascii 1..1) to 0..0.

    ^
```

**Comment by MeWhenI** [comment]
I was able to make all 3 examples throw the desired error by deleting this line from `getType.ts`:
https://github.com/polygolf-lang/polygolf/blob/ecb528177b08f89c1922f3a35a487293ab83f307/src/common/getType.ts#L59
I don't yet understand this caching well enough to know how to properly fix the issue, but this seems to be the source.

**Comment by MichalMarsalek** [comment]
> I was able to make all 3 examples throw the desired error by deleting this line from `getType.ts`:
> 
> https://github.com/polygolf-lang/polygolf/blob/ecb528177b08f89c1922f3a35a487293ab83f307/src/common/getType.ts#L59
> 
> 
> I don't yet understand this caching well enough to know how to properly fix the issue, but this seems to be the source.

Yes, it is the issue. Each node can have a type cached and the cache key is the object reference. Jared's immutable trees implementation encourages reusing of nodes. The assumption is that if the node is reused, it represents the same node and it must have a same type. This assumption is broken when a node is reused in different variants where their types should be independent.
Instantiating the variants should be deep cloning the trees or something. I tried to do that but faced other issues.
