### ISSUE TITLE
size[Array] op

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#287]
There is currently no op to get an array's size, should probably have one for consistency sake.

**Comment by MichalMarsalek** [comment]
Hmm that was intentional as I didn't see the benefit of having this op. I guess size of an array could be 2 bytes in some languages, which would be shorter than the int literal of its size, if that size is >99?

**Comment by MeWhenI** [comment]
Ah ok word that makes sense.
