### ISSUE TITLE
JS loop variable not an int

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#291]
[Playground link](https://polygolf-lang.github.io/?source=for%20%24a%200%2016%20%7B%0A%20%20%20%20println%20(%2B%20%24a%2020)%3B%0A%7D%3B%0A%0A&language=Javascript&objective=bytes&getAllVariants=true)

**Expected output**

```js
for(a in{}+1)print(20+~~a)
```

**Comment**
This form of looping seems to result in `a` being something other than an int. Not sure what exactly is going on under the hood but the output of the generated JS code is incorrect.

**Comment by MichalMarsalek** [comment]
Oh yes, keys are converted to strings right?

**Comment by MeWhenI** [comment]
Seems like it yeah
