### ISSUE TITLE
Take advantage of returning assignments

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#322]
Perform transformations like:
```javascript
a=3;b=a*c-a
c++;d*=c
e*=f;f++
```
=>
```javascript
b=(a=3)*c-a
d*=++c
e*=f++
```
This should probably wait for resolution of #272 since this functionality relies on keeping track of the order that assignments are performed in.

**Comment by MichalMarsalek** [comment]
Duplicate of #137 .
