### ISSUE TITLE
Validate type annotations

### ISSUE THREAD

**Issue by MichalMarsalek** [polygolf-lang/polygolf#345]
Check that the annotated type has a nonempty intersection with the calculated type.
Consider even checking that the annotation is a subtype of the calculated type.

**Comment by jared-hughes** [comment]
Typescript checks for nonempty intersection with "as":

```ts
const x: string = "a"
const y = x as 5;
```

> Conversion of type 'string' to type '5' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

And for supertype with a variable annotation:

```ts
const x: string = "b"
const y: "a" = x;
```

> Type 'string' is not assignable to type '"a"'.

**Comment by MichalMarsalek** [comment]
That's a good context and it's one that I had in mind when creating the issue. This is the minimum that we should do, but I cannot think of a case where the calculated type would be too narrow in Polygon, so maybe we can be more strict than ts and only allow narrowing the inferred type with the annotation.

**Comment by MichalMarsalek** [comment]
Contained in #354 .

**Comment by MichalMarsalek** [comment]
Contained in https://github.com/polygolf-lang/polygolf/issues/354 .
