### ISSUE TITLE
Standardize array copy behavior

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#347]
[Playground link](https://polygolf-lang.github.io/?source=%24a%20%3C-%20(list%201%202%203)%3B%0A%24b%20%3C-%20%24a%3B%0A%24c%20%3C-%20(%40%200)%3B%0A%24b%20%40%3C-%202%202%3B%0Aprint%20(%40%20%24a%202)%3B%0Aprint%20(%40%20%24b%202)%3B&language=all&objective=bytes&getAllVariants=false&compile=true)

**Comment**
There is variance between langs of whether array assignment makes a deep copy or a shallow copy. Most langs currently make shallow copies. Which behavior should be default, and should the alternate be supported in some way?

**Comment by MichalMarsalek** [comment]
Reference aliasing sounds like an absolute pain to handle.
