### ISSUE TITLE
Coconut golfs

### ISSUE THREAD

**Issue by MichalMarsalek** [polygolf-lang/polygolf#370]
- different forms of function applications
  Could be implemented similar to how `f(x)` => `f x` & `f(x)` => `x.f` is done for Nim.
  https://github.com/polygolf-lang/polygolf/blob/c849d1f8b3e2cfc39f443c478cf3bd3f3e434df7/src/languages/nim/plugins.ts#L89
  - [Implicit application/multiplication](https://coconut.readthedocs.io/en/latest/DOCS.html#implicit-function-application-and-coefficients)
  - [Pipes ](https://coconut.readthedocs.io/en/latest/DOCS.html#pipes)
  - [Infix functions](https://coconut.readthedocs.io/en/latest/DOCS.html#infix-functions)

**Comment by Steffan153** [comment]
- `2*x` => `2x`
